mse:
  target: pdetransformer.metric.SimulationMSE
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}
ae:
  target: pdetransformer.metric.SimulationAE
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}


accuracy:
  target: topotransformer.metric.SimulationAccuracy
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}
    threshold: ${threshold_accuracy}
    #sel_channels_input: ${data.params.sel_channels_input}
    #sel_channels_output: ${data.params.sel_channels_target}

sdf_mse:
  target: topotransformer.metric.SdfMSE
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}
    threshold: ${threshold_accuracy}

sdf_mae:
  target: topotransformer.metric.SdfMAE
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}
    threshold: ${threshold_accuracy}

entropy:
  target: topotransformer.metric.TopologyEntropy
  params:
    frequency: 1
    num_tasks: 4
    max_length: 1
    dataset_names: ${data.params.dataset_names}

