setup_callback:
    target: "pdetransformer.callback.setup_callback.SetupCallback"
    params:
        resume: ${runtime.resume}
        logdir: ${runtime.logdir}
        ckptdir: ${runtime.checkpoint_dir}
        cfgdir: ${runtime.config_dir}

model_summary:
    target: "lightning.pytorch.callbacks.ModelSummary"
    params:
        max_depth: 10

learning_rate_logger:
    target: "lightning.pytorch.callbacks.LearningRateMonitor"
    params:
        logging_interval: "step"

model_checkpoint:
    target: "lightning.pytorch.callbacks.ModelCheckpoint"
    params:
        dirpath: ${runtime.checkpoint_dir}
        filename: "{epoch:06}"
        verbose: True
        save_last: True
        monitor: ${model.params.monitor}
        save_top_k: 3

images:
    target: topotransformer.callback.MultiTaskImageLogger
    params:
        frequency: ${frequency_log_images}
        num_frames: 1
        num_inference_steps: ${num_sampling_steps}
        randomize: False
        max_images: 10
        test_only: True
        sel_denorm_channels: ${sel_denorm_channels}
        prepare_plots:
            target: pdetransformer.data.pbdl_module.prepare_plots
imagesAll:
    target: topotransformer.callback.MultiTaskImageLoggerALL
    params:
        frequency: ${frequency_log_images}
        num_frames: 1
        num_inference_steps: ${num_sampling_steps}
        randomize: False
        max_images: 10
        test_only: True
        sel_denorm_channels: ${sel_denorm_channels}
        threshold: ${threshold_accuracy}

        prepare_plots:
            target: pdetransformer.data.pbdl_module.prepare_plots
